site_name: loxilb
site_url: https://loxilb-io.github.io/loxilbdocs 
theme:
    name: readthedocs
    analytics:
        gtag: G-21G7NBL2BN 

extra:
    version: v0.8.3 (Latest)

plugins:
  - mermaid2
